# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(default='http://', max_length=8)),
                ('long_url', models.CharField(max_length=100)),
                ('create_date', models.CharField(max_length=10)),
                ('short_url', models.CharField(max_length=10)),
                ('click_numbers', models.IntegerField(default=0)),
            ],
        ),
    ]
